server:
  port: 8081

# datasource
spring:
    datasource:
      url: jdbc:mysql://localhost:3306/eqpmanage?serverTimezone=UTC&useAffectedRows=true
      username: root
      password: 123
      driver-class-name: com.mysql.cj.jdbc.Driver
logging:
    level:
      com.learnhow.springboot.mybatis.dao: debug
#分页插件配置
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
