server:
  port: 8081

# datasource
spring:
    datasource:
      url: jdbc:mysql://localhost:3306/sysgl?serverTimezone=UTC&useAffectedRows=true
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
logging:
    level:
      com.learnhow.springboot.mybatis.dao: debug
